module Heroes
{
export interface Hero {
    readonly name: string;
    readonly alternateName?: string;
    readonly image: string;
    readonly sounds: string[];
}

export var Strength: Hero[][] = [
    [
        { name: 'Earthshaker', image: 'earthshaker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/30/Erth_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/19/Erth_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/73/Erth_ability_echo_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/09/Erth_level_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e1/Erth_move_06.mp3' ] },
        { name: 'Sven', image: 'sven_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9b/Sven_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Sven_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5b/Sven_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3f/Sven_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cc/Sven_level_03.mp3' ] },
        { name: 'Tiny', image: 'tiny_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0b/Tiny_cast_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c3/Tiny_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/20/Tiny_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6e/Tiny_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9a/Tiny_ability_toss_11.mp3' ] },
        { name: 'Kunkka', image: 'kunkka_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f2/Kunk_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/62/Kunk_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d4/Kunk_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9f/Kunk_ability_xmark_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Kunk_ability_ghostshp_03.mp3' ] },
        { name: 'Beastmaster', image: 'beastmaster_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c4/Beas_spawn_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a0/Beas_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/15/Beas_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/16/Beas_ability_summonsbird_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1c/Beas_level_01.mp3' ] },
        { name: 'Dragon Knight', image: 'dragon_knight_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/48/DK_drag_spawn_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/43/DK_drag_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/11/DK_drag_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/DK_drag_level_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fa/DK_drag_kill_01.mp3' ] },
        { name: 'Clockwerk', image: 'rattletrap_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/89/Ratt_move_22.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/80/Ratt_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/04/Ratt_move_23.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dd/Ratt_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/57/Ratt_ability_flare_06.mp3' ] },
        { name: 'Omniknight', image: 'omniknight_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4d/Omni_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4d/Omni_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1e/Omni_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/82/Omni_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f2/Omni_level_06.mp3' ] },
        { name: 'Huskar', image: 'huskar_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d9/Husk_spawn_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fb/Husk_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e3/Husk_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/38/Husk_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/82/Husk_level_04.mp3' ] },
        { name: 'Alchemist', image: 'alchemist_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0c/Alch_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b2/Alch_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/98/Alch_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b5/Alch_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/02/Alch_attack_03.mp3' ] },
        { name: 'Brewmaster', image: 'brewmaster_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/10/Brew_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/30/Brew_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6d/Brew_attack_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/94/Brew_ability_thunderclap_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ec/Brew_level_06.mp3' ] },
        { name: 'Treant Protector', image: 'treant_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/25/Treant_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/81/Treant_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6e/Treant_move_24.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f2/Treant_attack_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Treant_ability_livingarmor_04.mp3' ] },
        { name: 'Io', alternateName: 'Wisp', image: 'wisp_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d2/Wisp_Battlebegins.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5f/Wisp_Move02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/01/Wisp_Attack.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/ff/Wisp_Levelup.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Wisp_Death.mp3' ] },
        { name: 'Centaur Warrunner', image: 'centaur_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b8/Cent_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/16/Cent_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/01/Cent_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1e/Cent_levelup_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ea/Cent_move_13.mp3' ] },
        { name: 'Timbersaw', image: 'shredder_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1d/Timb_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/60/Timb_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e8/Timb_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b7/Timb_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/08/Timb_levelup_02.mp3' ] },
        { name: 'Bristleback', image: 'bristleback_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7d/Bristle_begin_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e9/Bristle_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3f/Bristle_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Bristle_attack_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a7/Bristle_attack_18.mp3' ] },
        { name: 'Tusk', image: 'tusk_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c0/Tusk_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4d/Tusk_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9d/Tusk_move_25.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f7/Tusk_attack_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5f/Tusk_levelup_08.mp3' ] },
        { name: 'Elder Titan', image: 'elder_titan_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e8/Elder_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/61/Elder_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/55/Elder_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/04/Elder_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/44/Elder_ancestralspirit_03.mp3' ] },
        { name: 'Legion Commander', image: 'legion_commander_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/27/Legcom_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Legcom_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bd/Legcom_move_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/74/Legcom_duelfailure_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/ff/Legcom_levelup_01.mp3' ] },
        { name: 'Earth Spirit', image: 'earth_spirit_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3c/Earthspi_spawn_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/72/Earthspi_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f8/Earthspi_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/83/Earthspi_move_22.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/32/Earthspi_levelup_05.mp3' ] },
        { name: 'Phoenix', image: 'phoenix_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/da/Phoenix_bird_victory.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/89/Phoenix_bird_moving01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d4/Phoenix_bird_moving02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a5/Phoenix_bird_attack.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8d/Phoenix_bird_level_up.mp3' ] },
    ],
    [
        { name: 'Axe', image: 'axe_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c1/Axe_spawn_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c1/Axe_spawn_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b9/Axe_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/54/Axe_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/da/Axe_deny_16.mp3' ] },
        { name: 'Pudge', image: 'pudge_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d5/Pud_spawn_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2e/Pud_move_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/02/Pud_move_16.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/38/Pud_ability_hook_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fd/Pud_ability_devour_02.mp3' ] },
        { name: 'Sand King', image: 'sand_king_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b4/Sand_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f8/Skg_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ed/Skg_move_22.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d9/Skg_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0f/Skg_level_03.mp3' ] },
        { name: 'Slardar', image: 'slardar_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a1/Slar_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/76/Slar_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5a/Slar_ability_ampdam_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/06/Slar_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8b/Slar_level_02.mp3' ] },
        { name: 'Tidehunter', image: 'tidehunter_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4f/Tide_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Tide_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5a/Tide_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/69/Tide_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/Tide_level_01.mp3' ] },
        { name: 'Wraith King', image: 'skeleton_king_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/Wraith_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c3/Wraith_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a0/Wraith_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/18/Wraith_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1f/Wraith_level_01.mp3' ] },
        { name: 'Lifestealer', alternateName: 'Naix', image: 'life_stealer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2e/Lifest_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/53/Lifest_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5a/Lifest_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/79/Lifest_levelup_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ac/Lifest_death_06.mp3' ] },
        { name: 'Night Stalker', image: 'night_stalker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d9/Nstalk_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Nstalk_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6c/Nstalk_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a3/Nstalk_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/55/Nstalk_attack_13.mp3' ] },
        { name: 'Doom', image: 'doom_bringer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/eb/Doom_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5b/Doom_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/52/Doom_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a1/Doom_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/52/Doom_level_06.mp3' ] },
        { name: 'Spirit Breaker', image: 'spirit_breaker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/76/Spir_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dc/Spir_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dc/Spir_move_19.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Spir_attack_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/88/Spir_level_02.mp3' ] },
        { name: 'Lycan', image: 'lycan_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9a/Lycan_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ad/Lycan_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2c/Lycan_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e7/Lycan_level_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/32/Lycan_kill_07.mp3' ] },
        { name: 'Chaos Knight', image: 'chaos_knight_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Chaknight_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a8/Chaknight_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8c/Chaknight_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/36/Chaknight_ability_phantasm_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b9/Chaknight_levelup_01.mp3' ] },
        { name: 'Undying', image: 'undying_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b5/Undying_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bc/Undying_move_16.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/42/Undying_move_19.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fd/Undying_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1d/Undying_levelup_03.mp3' ] },
        { name: 'Magnus', image: 'magnataur_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/75/Magn_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/97/Magn_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Magn_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5d/Magn_attack_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dd/Magn_levelup_04.mp3' ] },
        { name: 'Abaddon', image: 'abaddon_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b4/Abad_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bd/Abad_begin_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fc/Abad_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dc/Abad_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fe/Abad_cast_02.mp3' ] },
        { name: 'Underlord', image: 'abyssal_underlord_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/20/Abys_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5c/Abys_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0c/Abys_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9e/Abys_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/87/Abys_levelup_02.mp3' ] },
    ]
];


export var Agility: Hero[][] = [
    [
        { name: 'Anti-Mage', alternateName: 'Magina', image: 'antimage_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7f/Anti_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ec/Anti_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cb/Anti_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3d/Anti_attack_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5b/Anti_kill_06.mp3' ] },
        { name: 'Drow Ranger', alternateName: 'Traxex', image: 'drow_ranger_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Drow_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e8/Dro_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/39/Dro_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b6/Dro_respawn_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5b/Dro_move_07.mp3' ] },
        { name: 'Juggernaut', image: 'juggernaut_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/22/Jug_cast_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/37/Jug_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/28/Jug_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ec/Jug_ability_bladefury_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d4/Jug_level_04.mp3' ] },
        { name: 'Mirana', alternateName: 'Priestess of the Moon', image: 'mirana_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Mir_cast_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Mir_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b4/Mir_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7d/Mir_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b3/Mir_levelup_05.mp3' ] },
        { name: 'Morphling', image: 'morphling_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9d/Mrph_spawn_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/43/Mrph_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1c/Mrph_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/32/Mrph_level_02a.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/55/Mrph_respawn_03.mp3' ] },
        { name: 'Phantom Lancer', image: 'phantom_lancer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/72/Plance_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/76/Plance_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c6/Plance_move_clone_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f1/Plance_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0e/Plance_levelup_04.mp3' ] },
        { name: 'Vengeful Spirit', image: 'vengefulspirit_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7e/Vng_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1e/Vng_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8f/Vng_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b5/Vng_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c8/Vng_levelup_01.mp3' ] },
        { name: 'Riki', alternateName: 'Rikimaru', image: 'riki_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0a/Riki_ability_invis_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Riki_move_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/23/Riki_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dc/Riki_cast_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a7/Riki_level_02.mp3' ] },
        { name: 'Sniper', image: 'sniper_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/99/Snip_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7a/Snip_move_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/ce/Snip_move_20.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/76/Snip_tf2_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/17/Snip_ability_shrapnel_03.mp3' ] },
        { name: 'Templar Assassin', image: 'templar_assassin_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6e/Temp_begins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f5/Temp_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d5/Temp_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/43/Temp_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a7/Temp_levelup_05.mp3' ] },
        { name: 'Luna', image: 'luna_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/02/Luna_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/86/Luna_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6e/Luna_attack_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/44/Luna_ability_lucentbeam_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3c/Luna_levelup_01.mp3' ] },
        { name: 'Bounty Hunter', image: 'bounty_hunter_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/30/Bount_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/05/Bount_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e1/Bount_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/50/Bount_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c7/Bount_ability_windwalk_04.mp3' ] },
        { name: 'Ursa', image: 'ursa_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3d/Ursa_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/33/Ursa_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/45/Ursa_move_23.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3c/Ursa_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Ursa_levelup_08.mp3' ] },
        { name: 'Gyrocopter', image: 'gyrocopter_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cc/Gyro_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/29/Gyro_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0e/Gyro_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a0/Gyro_move_25.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/51/Gyro_homing_missile_fire_02.mp3' ] },
        { name: 'Lone Druid', alternateName: 'Syllabear', image: 'lone_druid_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Lone_druid_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/53/Lone_druid_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/79/Lone_druid_attack_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/19/Lone_druid_ability_spiritbear_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/04/Lone_druid_level_02.mp3' ] },
        { name: 'Naga Siren', image: 'naga_siren_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b0/Naga_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ae/Naga_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ad/Naga_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d4/Naga_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2d/Naga_levelup_01.mp3' ] },
        { name: 'Troll Warlord', image: 'troll_warlord_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/08/Troll_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e2/Troll_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3e/Troll_move_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bd/Troll_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/00/Troll_levelup_01.mp3' ] },
        { name: 'Ember Spirit', image: 'ember_spirit_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/65/Embr_spawn_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/88/Embr_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/27/Embr_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/41/Embr_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ad/Embr_searingchains_02.mp3' ] },
        { name: 'Monkey King', alternateName: 'Sun Wukong', image: 'monkey_king_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4e/Monkey_spawn_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/ca/Mk_takeover_vo.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/44/Monkey_spawn_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/88/Monkey_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4f/Monkey_attack_11.mp3' ] }
    ],
    [
        { name: 'Bloodseeker', image: 'bloodseeker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/62/Blod_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f7/Blod_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/be/Blod_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/80/Blod_level_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d5/Blod_ability_thirst_03.mp3' ] },
        { name: 'Shadow Fiend', image: 'nevermore_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a3/Nev_spawn_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/83/Nev_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/80/Nev_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/01/Nev_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e8/Nev_level_07.mp3' ] },
        { name: 'Razor', image: 'razor_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/99/Raz_spawn_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9c/Raz_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cf/Raz_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6e/Raz_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b2/Raz_ability_static_02.mp3' ] },
        { name: 'Venomancer', image: 'venomancer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/74/Venm_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4f/Venm_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/14/Venm_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9a/Venm_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/58/Venm_level_05.mp3' ] },
        { name: 'Faceless Void', image: 'faceless_void_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/96/Face_cast_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/53/Face_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e4/Face_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bc/Face_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8b/Face_ability_chronos_03.mp3' ] },
        { name: 'Phantom Assassin', image: 'phantom_assassin_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f2/Phass_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/57/Phass_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Phass_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dd/Phass_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/11/Phass_level_06.mp3' ] },
        { name: 'Viper', image: 'viper_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d3/Vipe_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e8/Vipe_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Vipe_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/51/Vipe_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4d/Vipe_level_02.mp3' ] },
        { name: 'Clinkz', image: 'clinkz_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d1/Clinkz_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/de/Clinkz_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/51/Clinkz_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Clinkz_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bf/Clinkz_kill_04.mp3' ] },
        { name: 'Broodmother', image: 'broodmother_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/eb/Broo_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/18/Broo_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1c/Broo_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e2/Broo_attack_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/41/Broo_ability_spawn_10.mp3' ] },
        { name: 'Weaver', image: 'weaver_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6d/Weav_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/52/Weav_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e9/Weav_move_19.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/40/Weav_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/46/Weav_level_01.mp3' ] },
        { name: 'Spectre', image: 'spectre_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/29/Spec_cast_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b3/Spec_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Spec_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9f/Spec_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/10/Spec_level_03.mp3' ] },
        { name: 'Meepo', image: 'meepo_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dd/Meepo_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/44/Meepo_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/33/Meepo_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b2/Meepo_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/df/Meepo_levelup_02.mp3' ] },
        { name: 'Nyx Assassin', image: 'nyx_assassin_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/76/Nyx_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5e/Nyx_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/13/Nyx_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Nyx_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/14/Nyx_levelup_06.mp3' ] },
        { name: 'Slark', image: 'slark_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d1/Slark_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4d/Slark_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2f/Slark_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4f/Slark_attack_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f4/Slark_levelup_01.mp3' ] },
        { name: 'Medusa', image: 'medusa_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cc/Medus_begin_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bf/Medus_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fe/Medus_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/73/Medus_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0b/Medus_levelup_04.mp3' ] },
        { name: 'Terrorblade', image: 'terrorblade_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/72/Terr_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/94/Terr_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/79/Terr_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b5/Terr_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ef/Terr_morph_metamorphosis_05.mp3' ] },
        { name: 'Arc Warden', image: 'arc_warden_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a7/Arcwar_battlebegins_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6c/Arcwar_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Arcwar_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/59/Arcwar_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0a/Arcwar_magnetic_field_05.mp3' ] },
    ]
];


export var Intelligence: Hero[][] = [
    [
        { name: 'Crystal Maiden', alternateName: 'Rylai', image: 'crystal_maiden_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/45/Cm_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/be/Cm_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d2/Cm_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e6/Cm_levelup_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/85/Cm_attack_04.mp3' ] },
        { name: 'Puck', image: 'puck_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/09/Puck_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/Puck_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b3/Puck_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/45/Puck_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f9/Puck_level_03.mp3' ] },
        { name: 'Storm Spirit', image: 'storm_spirit_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/19/Stormspirit_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f6/Ss_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/27/Ss_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7f/Ss_ability_lightning_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Stormspirit_levelup_01.mp3' ] },
        { name: 'Windranger', image: 'windrunner_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4b/Wind_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/ff/Wind_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/17/Wind_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a0/Wind_attack_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4e/Wind_level_02.mp3' ] },
        { name: 'Zeus', image: 'zuus_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fd/Zuus_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a6/Zuus_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d5/Zuus_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b5/Zuus_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d6/Zuus_level_04.mp3' ] },
        { name: 'Lina', image: 'lina_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fb/Lina_spawn_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/be/Lina_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/87/Lina_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bb/Lina_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ac/Lina_level_01.mp3' ] },
        { name: 'Shadow Shaman', alternateName: 'Rhasta', image: 'shadow_shaman_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b8/Shad_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2d/Shad_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/Shad_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f7/Shad_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/22/Shad_level_03.mp3' ] },
        { name: 'Tinker', image: 'tinker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0d/Tink_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2a/Tink_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bb/Tink_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Tink_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/95/Tink_levelup_05.mp3' ] },
        { name: "Nature's Prophet", alternateName: 'Furion', image: 'furion_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f7/Furi_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3b/Furi_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3c/Furi_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/28/Furi_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0e/Furi_ability_force_04.mp3' ] },
        { name: 'Enchantress', image: 'enchantress_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Ench_start_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f1/Ench_spawn_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/42/Ench_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5e/Ench_move_20.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9f/Ench_attack_05.mp3' ] },
        { name: 'Jakiro', image: 'jakiro_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c1/Jak_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d8/Jak_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/97/Jak_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ac/Jak_level_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1e/Jak_kill_04.mp3' ] },
        { name: 'Chen', image: 'chen_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b8/Chen_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Chen_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/50/Chen_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d7/Chen_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1c/Chen_ability_handgod_03.mp3' ] },
        { name: 'Silencer', image: 'silencer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/12/Silen_spawn_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/de/Silen_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7a/Silen_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/70/Silen_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a5/Silen_level_02.mp3' ] },
        { name: 'Ogre Magi', image: 'ogre_magi_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/5b/Ogmag_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/44/Ogmag_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/cd/Ogmag_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b4/Ogmag_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f5/Ogmag_level_01.mp3' ] },
        { name: 'Rubick', image: 'rubick_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ee/Rubick_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e3/Rubick_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/db/Rubick_move_14.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1b/Rubick_attack_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/af/Rubick_levelup_02.mp3' ] },
        { name: 'Disruptor', image: 'disruptor_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/12/Dis_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/55/Dis_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f9/Dis_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/38/Dis_thunderstrike_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fe/Dis_levelup_02.mp3' ] },
        { name: 'Keeper of the Light', alternateName: 'kotl', image: 'keeper_of_the_light_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b9/Keep_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Keep_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6d/Keep_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f1/Keep_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/ba/Keep_chakramagic_03.mp3' ] },
        { name: 'Skywrath Mage', image: 'skywrath_mage_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/36/Drag_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/87/Drag_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/75/Drag_move_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/12/Drag_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/40/Drag_levelup_01.mp3' ] },
        { name: 'Oracle', image: 'oracle_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f3/Orac_battlebegins_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8c/Orac_move_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/58/Orac_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/95/Orac_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bf/Orac_levelup_01.mp3' ] },
        { name: 'Techies', image: 'techies_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/dc/Tech_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/34/Tech_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/45/Tech_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/50/Tech_move_60.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c8/Tech_cast_02.mp3' ] },
    ],
    [
        { name: 'Bane', image: 'bane_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7a/Bane_spawn_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/12/Bane_spawn_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fe/Bane_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/87/Bane_level_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7b/Bane_ability_nightmare_01.mp3' ] },
        { name: 'Lich', image: 'lich_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/05/Lich_rare_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d5/Lich_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/60/Lich_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/50/Lich_ability_nova_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Lich_ability_ritual_01.mp3' ] },
        { name: 'Lion', image: 'lion_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6f/Lion_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fb/Lion_level_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d0/Lion_kill_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d3/Lion_lasthit_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4a/Lion_respawn_01.mp3' ] },
        { name: 'Witch Doctor', image: 'witch_doctor_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ed/Wdoc_attack_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/91/Wdoc_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/10/Wdoc_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/09/Wdoc_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/64/Wdoc_level_08.mp3' ] },
        { name: 'Enigma', image: 'enigma_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/78/Enig_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2f/Enig_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/de/Enig_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7b/Enig_ability_black_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fb/Enig_level_03.mp3' ] },
        { name: 'Necrophos', image: 'necrolyte_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/fb/Necr_cast_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ec/Necr_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ea/Necr_move_11.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Necr_attack_15.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7e/Necr_level_05.mp3' ] },
        { name: 'Warlock', image: 'warlock_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/32/Warl_cast_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2b/Warl_move_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4c/Warl_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/32/Warl_attack_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ea/Warl_level_10.mp3' ] },
        { name: 'Queen of Pain', alternateName: 'Qop', image: 'queenofpain_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3a/Pain_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/61/Pain_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ae/Pain_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/89/Pain_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6b/Pain_levelup_02.mp3' ] },
        { name: 'Death Prophet', image: 'death_prophet_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2b/Dpro_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/69/Dpro_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f9/Dpro_attack_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8b/Dpro_exorcism_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/08/Dpro_levelup_03.mp3' ] },
        { name: 'Pugna', image: 'pugna_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/80/Pugna_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/50/Pugna_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/02/Pugna_move_12.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a2/Pugna_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/7f/Pugna_level_05.mp3' ] },
        { name: 'Dazzle', image: 'dazzle_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/c/c3/Dazz_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8f/Dazz_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/39/Dazz_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9c/Dazz_ability_shalgrave_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/bd/Dazz_notyet_03.mp3' ] },
        { name: 'Leshrac', image: 'leshrac_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/da/Lesh_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Lesh_move_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9d/Lesh_attack_09.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/22/Lesh_ability_edict_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d0/Lesh_level_03.mp3' ] },
        { name: 'Dark Seer', image: 'dark_seer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/91/Dkseer_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/8e/Dkseer_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/72/Dkseer_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/85/Dkseer_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f7/Dkseer_level_06.mp3' ] },
        { name: 'Batrider', image: 'batrider_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/9e/Bat_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b0/Bat_battlebegins_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/e0/Bat_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/af/Bat_move_17.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/07/Bat_attack_03.mp3' ] },
        { name: 'Ancient Apparition', image: 'ancient_apparition_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/35/Appa_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2a/Appa_spawn_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/18/Appa_move_08.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/04/Appa_ability_touch_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ae/Appa_level_02.mp3' ] },
        { name: 'Invoker', image: 'invoker_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/09/Invo_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/db/Invo_level_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/2a/Invo_move_18.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/9/92/Invo_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b6/Invo_ability_invoke_01.mp3' ] },
        { name: 'Outworld Devourer', image: 'obsidian_destroyer_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6c/Odest_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/5/57/Odest_move_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/7/71/Odest_move_13.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/e/ef/Odest_attack_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/ad/Odest_levelup_03.mp3' ] },
        { name: 'Shadow Demon', image: 'shadow_demon_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/02/Shadow_demon_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a8/Shadow_demon_move_02.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/a/a4/Shadow_demon_move_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/68/Shadow_demon_attack_03.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/d/d3/Shadow_demon_level_up_04.mp3' ] },
        { name: 'Visage', image: 'visage_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/f/f8/Visa_begin_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1e/Visa_move_05.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/b/b0/Visa_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/4e/Visa_attack_06.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/27/Visa_levelup_01.mp3' ] },
        { name: 'Winter Wyvern', image: 'winter_wyvern_sb.png', sounds: [ 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1b/Winwyv_battlebegins_01.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/3d/Winwyv_move_04.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/1/1b/Winwyv_move_10.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/0/0c/Winwyv_attack_07.mp3', 'https://hydra-media.cursecdn.com/dota2.gamepedia.com/3/34/Winwyv_levelup_01.mp3' ] },
    ]
];


/**
 * Get a list with all the heroes.
 */
export function getAll()
    {
    var all: Hero[] = [];

    for (let a = 0 ; a < Strength.length ; a++)
        {
        all = all.concat( Strength[ a ] );
        }

    for (let a = 0 ; a < Agility.length ; a++)
        {
        all = all.concat( Agility[ a ] );
        }

            for (let a = 0 ; a < Intelligence.length ; a++)
        {
        all = all.concat( Intelligence[ a ] );
        }

    return all;
    }
}
